name: conda-fmi 2 Docker

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]

env:
  DIRECTORY: conda-fmi
  # DATE: # see below

jobs:

  docker-build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    name: Build, run, and push
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variable
        run: |
          echo "DATE=$(date +%s)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd ${{ env.DIRECTORY }}
          docker build . -f Dockerfile --build-arg CONDA_ENV=${{ env.DIRECTORY }} \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DIRECTORY }} \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DIRECTORY }}:${{ env.DATE }} \
            
          
      - name: Run Docker image locally
        run: |
          echo "<DOCKER_USERNAME>/${{ env.DIRECTORY }}:${{ env.DATE }}"
          docker run -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DIRECTORY }}:${{ env.DATE }}
          
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DIRECTORY }} --all-tags
          
      - name: Stats
        run: |
          docker image ls ${{ secrets.DOCKER_USERNAME }}/${{ env.DIRECTORY }}
          docker history ${{ secrets.DOCKER_USERNAME }}/${{ env.DIRECTORY }}

  docker-pull-run:
    runs-on: ubuntu-latest
    needs:
      - docker-build-push
    strategy:
      fail-fast: false
      
    name: Pull, and run
    steps:          
      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.DIRECTORY }}  #:${{ env.DATE }}
          
      - name: Run Docker image locally
        run: |
          docker run ${{ secrets.DOCKER_USERNAME }}/${{ env.DIRECTORY }}
